#ifndef IOFUSION_TEST_SUPPORT_H
#define IOFUSION_TEST_SUPPORT_H

#include <cstdint>

void resetMockState();
void setDigitalPin(uint8_t pin, bool high);

void test_analog_sampler_basic();
void test_analog_sampler_invalid_channel();
void test_analog_sampler_coalesces_pending_refresh_requests();
void test_digital_signal_meter_frequency_and_duty();
void test_digital_signal_meter_keeps_two_edge_windows_in_cycle_mode();
void test_digital_signal_meter_uses_completed_periods_for_three_edge_windows();
void test_digital_signal_meter_reports_low_frequency_from_period();
void test_digital_signal_meter_clears_stale_frequency_after_missing_edges();
void test_digital_signal_meter_stale_aging_advances_while_window_waits_for_loop();
void test_digital_signal_meter_ignores_edges_that_happened_while_window_was_pending();
void test_quadrature_signal_generator_steps();
void test_quadrature_signal_generator_steps_backward_on_active_high_down();
void test_avr_timer1_pwm_begin_sets_timer_registers();
void test_avr_timer1_pwm_set_duty_updates_compare_register();
void test_avr_timer1_pwm_stop_drives_outputs_low();
void test_avr_timer2_scheduler_begin_sets_ctc_registers();
void test_avr_timer2_scheduler_begin_accepts_valid_zero_ocr();
void test_avr_timer2_scheduler_callback_lifecycle();
void test_serial_command_protocol_status_response_envelope();
void test_serial_command_protocol_capabilities_response_lists_commands_and_pins();
void test_serial_command_protocol_rejects_out_of_range_pwm_duty();
void test_serial_command_protocol_analog_query_uses_response_envelope();
void test_serial_command_protocol_digital_query_uses_compact_scaled_units();
void test_serial_command_protocol_encoder_query_uses_compact_fields();
void test_serial_command_protocol_discards_oversized_frame_until_newline();

#endif // IOFUSION_TEST_SUPPORT_H